app:
  name: short-app
  image: antonlarichev/short-app
  version: v1.4
  components: frontend
  port: 80
  replicas: 1
  limits:
    memory: "128Mi"
    cpu: "100m"

api:
  name: short-api
  image: antonlarichev/short-api
  version: v1.0
  components: backend
  port: 3000
  replicas: 1
  limits:
    memory: "500Mi"
    cpu: "200m"
  env: DATABASE_URL

postgres:
  name: postgres
  image: antonlarichev/short-api
  version: v1.0
  components: backend
  port: 5432
  limits:
    memory: "500Mi"
    cpu: "200m"

database:
  user: demo
  password: demo
  db: demo
  host: postgres-clusterip
